### PR TITLE
OSE state changes for torch and lantern

### PR DESCRIPTION
**Pull request by Andrew-Staggs**
Wanted to have a state change for the light sources for OSE. The json objects were missing the state change. Hoping this fixes the issue and it can then be toggled on and off.

### CODE REVIEW

**Comment by lupestro** [comment]
The default value for "states" is 2 (representing on, off), and the "light" value will either be a single object or an array with one object in it for the "on" lighting. Hooded lanterns (and possibly some other sources, of course) allow for two levels of light setting besides "off", so they get `"states": 3` and their "light" value is an array of two objects representing the "high" and "low" settings. "Flicking the Bic" for this repeatedly toggles across all three states.

What wasn't happening that you were hoping would happen with the change in this PR? Because the changes here won't affect any of the existing behavior unless there's a bug in the code, which is something I would need to know about.

**Comment by Andrew-Staggs** [comment]
Hi. Currently for OSE, there are two objects (torch and lantern). When attempting to use the toggle function to switch the state of the torch on or off, nothing is happening. I noticed the torch and lantern objects for OSE were missing the states variable which every other platform such as dnd5e 5e currently has. Like you mentioned, it represents the states of those objects but they are missing from the OSE objects in the sources.mjs file.

Regarding the lantern I can change that to be "states": 3 

If this isn't enough to solve the issue, I am be glad to hear what is needed.

Thanks.

**Comment by lupestro** [comment]
Thank you. “States”:2 is the correct value. Your experience would suggest the module’s fallback for missing states property isn’t working. I’ll add the explicit values you’ve supplied but I’ll also track down and fix the bug. All apologies!

**Comment by Andrew-Staggs** [comment]
Great. Thank you!

**Comment by lupestro** [comment]
Once we have the user experienced fixed by using your change, I'll go back and debug why omitting the "states" wasn't working.

**Comment by lupestro** [comment]
Published in 2.15.0 - I'll be debugging the issues with the defaults in another drop - possibly today (along with another recently reported bug)

**Pull request merged**
